import React, { useEffect } from 'react';
import Head from 'next/head';
import { useDispatch } from 'react-redux';
import { resetUser, setUser } from '@/state/slices/userStateSlice';

const Home = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setUser({
      loaded: true,
      user: 'hello',
    }));
    return () => {
      dispatch(resetUser());
    };
  }, [ dispatch ]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
